"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class test_signal_sequence_lcmt(object):
    __slots__ = ["pos", "rpy", "q_knee", "q_hip", "timestep"]

    __typenames__ = ["float", "float", "float", "float", "float"]

    __dimensions__ = [[100], [100], [100], [100], [100]]

    def __init__(self):
        self.pos = [ 0.0 for dim0 in range(100) ]
        self.rpy = [ 0.0 for dim0 in range(100) ]
        self.q_knee = [ 0.0 for dim0 in range(100) ]
        self.q_hip = [ 0.0 for dim0 in range(100) ]
        self.timestep = [ 0.0 for dim0 in range(100) ]

    def encode(self):
        buf = BytesIO()
        buf.write(test_signal_sequence_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>100f', *self.pos[:100]))
        buf.write(struct.pack('>100f', *self.rpy[:100]))
        buf.write(struct.pack('>100f', *self.q_knee[:100]))
        buf.write(struct.pack('>100f', *self.q_hip[:100]))
        buf.write(struct.pack('>100f', *self.timestep[:100]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != test_signal_sequence_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return test_signal_sequence_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = test_signal_sequence_lcmt()
        self.pos = struct.unpack('>100f', buf.read(400))
        self.rpy = struct.unpack('>100f', buf.read(400))
        self.q_knee = struct.unpack('>100f', buf.read(400))
        self.q_hip = struct.unpack('>100f', buf.read(400))
        self.timestep = struct.unpack('>100f', buf.read(400))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if test_signal_sequence_lcmt in parents: return 0
        tmphash = (0x6f00e04668c1232c) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if test_signal_sequence_lcmt._packed_fingerprint is None:
            test_signal_sequence_lcmt._packed_fingerprint = struct.pack(">Q", test_signal_sequence_lcmt._get_hash_recursive([]))
        return test_signal_sequence_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

